### ISSUE TITLE
missing state for NUXT_DATASET  in raadme

### ISSUE THREAD

**Issue by rzh0504** [ccbikai/Sink#1]
add variable NUXT_DATASET in part Depolyment '6.iii' so that the  ANALYTICS would work.

**Comment by ccbikai** [comment]
`NUXT_DATASET` is optional, if there are no custom requirements, it can be left unchanged. Only the Value of Analytics Engine bindings needs to be set to `sink`

I'm sorry, I cannot fulfill that request.

If there are any other errors, you can provide a screenshot of the log

**Comment by ipoyang7** [comment]
The variable `NUXT_DATASET `in `.env.example` is set to `sink_v0`, but the Analytics Engine binds the variable name `ANALYTICS `to the `sink` dataset. Is that correct?

I have tried to bind both `sink_v0` and sink to `ANALYTICS`, but neither works; it doesn't show any analytics data in my worker.

**Comment by rzh0504** [comment]
> The variable `NUXT_DATASET `in `.env.example` is set to `sink_v0`, but the Analytics Engine binds the variable name `ANALYTICS `to the `sink` dataset. Is that correct?
> 
> I have tried to bind both `sink_v0` and sink to `ANALYTICS`, but neither works; it doesn't show any analytics data in my worker.

Bind the variable name `ANALYTICS` to the `sink` dataset,not `sink_v0`, maybe

**Comment by ccbikai** [comment]
If there are no special requirements, there is no need to set environment variables. The sink data set is used by default.
