### ISSUE TITLE
save link not working

### ISSUE THREAD

**Issue by cirrusflyer** [ccbikai/Sink#10]
![Screenshot from 2024-05-31 14-26-47](https://github.com/ccbikai/Sink/assets/33668552/aa299bc1-32c0-485f-ad79-61eb27ed9c58)
I have everything setup and am able to login and see the entire system.  But when trying to create a link, on the empty link page, I see a "spinning" icon, and when I try to create the first link, the save button doesn't seem to work.

**Comment by laotoutou** [comment]
![image](https://github.com/ccbikai/Sink/assets/21292149/e829e608-4015-41fd-b345-135f393458e1)

Me too

**Comment by ccbikai** [comment]
Hello, check the binding of KV to see if it has been bound in both the production environment and the preview environment

The variable name of KV should be in uppercase `KV` , is it written incorrectly?

**Comment by laotoutou** [comment]
![image](https://github.com/ccbikai/Sink/assets/21292149/3b7d584c-3afe-4d24-8c9e-e0d549c47438)
![image](https://github.com/ccbikai/Sink/assets/21292149/aceede26-5aa1-400c-8d06-d6adc46bdcb8)

This configuration solved my problem.

**Comment by cirrusflyer** [comment]
Thanks.  I had the KV variable, but it wasn't assigned to a KV namespace.  I assigned KV to KV and it's working now.
