### ISSUE TITLE
Feature Request: Add TOTP-based Login for Enhanced Security

### ISSUE THREAD

**Issue by lainbo** [ccbikai/Sink#18]
First, thanks to the author for their effort in creating sink.

I suggest adding Time-based One-Time Password (TOTP) as an optional login method to enhance the security of user accounts.

Some of the better known short linking platforms have this feature, so I'm hoping that sink will support this.
1. [bitly - What is 2-factor authentication](https://support.bitly.com/hc/en-us/articles/230650187-What-is-2-factor-authentication)
2. [short.io - How to Enable 2-Factor Authentication](https://help.short.io/en/articles/4065798-how-to-enable-2-factor-authentication)
3. [Rebrandly - Two Factor Authentication (2FA)](https://support.rebrandly.com/hc/en-us/articles/360007220373-Two-Factor-Authentication-2FA)

**Comment by ccbikai** [comment]
Token is set to uuid, regularly modified, security is sufficient.

Will not introduce complex authentication for now

**Comment by lainbo** [comment]
> Token is set to uuid, regularly modified, security is sufficient.
> 
> Will not introduce complex authentication for now

Thanks for your reply
