### ISSUE TITLE
will it Support homepage to `/Dashboard`

### ISSUE THREAD

**Issue by jarlin8** [ccbikai/Sink#2]

**Comment by ccbikai** [comment]
You can try setting the environment variable `NUXT_HOME_URL` to https://github.com/ccbikai/Sink/blob/master/docs/configuration.md#nuxt_home_url

I haven't actually tested it, but I think it's possible. If it works, remember to give feedback.

I redirected http://s.mt.ci/

**Comment by jarlin8** [comment]
I have tested, but it seems not work

**Comment by ccbikai** [comment]
After modifying the environment variables, redeployment is required. I tried it and it worked https://s.mt.ci/

**Comment by jarlin8** [comment]
try again, `NUXT_HOME_URL`must be `https://domain.com/dashboard`,it worked,thank you!

**Comment by p0we7** [comment]
@ccbikai I have another request. I want the homepage to be blank, or my custom page. What should I do?

**Comment by ccbikai** [comment]
> @ccbikai I have another request. I want the homepage to be blank, or my custom page. What should I do?

Currently not supported, you need to modify the code yourself

**Comment by p0we7** [comment]
> > @ccbikai I have another request. I want the homepage to be blank, or my custom page. What should I do?
> 
> Currently not supported, you need to modify the code yourself

However, I am not very familiar with Nuxt. Can you tell me which files I should modify so that I can make the changes?
