### ISSUE TITLE
[suggestion] Improve cache hit rate with `cacheTtl`

### ISSUE THREAD

**Issue by twodft** [ccbikai/Sink#24]
> cacheTtl is a parameter that defines the length of time in seconds that a KV result is cached in the global network location it is accessed from.
 Defining the length of time in seconds is useful for reducing cold read latency on keys that are read relatively infrequently. cacheTtl is useful if your data is write-once or write-rarely.

https://developers.cloudflare.com/kv/api/read-key-value-pairs/#cachettl-parameter

**Comment by ccbikai** [comment]
The default cacheTtl is 1 minute, and if it's set too long, changes may take a while to take effect. I can make it a configurable item, allowing users to control it via environment variables

**Comment by ccbikai** [comment]
I made it into a configuration item, you can configure it using environment variables `NUXT_LINK_CACHE_TTL `

https://github.com/ccbikai/Sink/blob/master/docs/configuration.md#nuxt_link_cache_ttl
