### ISSUE TITLE
[REQUEST] pass params to the target

### ISSUE THREAD

**Issue by MAbarri** [ccbikai/Sink#27]
Hello, 

Your project is definitly the best thing that i found on github, amazing performance and very easy to use, 

In some cases, I need the shortlink to pass params to the target page for example : 

original link : 
https://example.com/xxxx/yyyyy/dynamicParam
or 
https://example.com/xxxx/yyyyy?param=dynamicParam

Generate shortlink can only redirect to the same static link 
if would be great if we can pass a param in the shortlink, something like this : 

https://mySinkInstance.com/mySlug/dynamicParam1/dynamicParam2/dynamicParam3

the dynamic params format get preserved as they are and added to the target link

https://targetlink.com/xxxx/yyyyy/dynamicParam1/dynamicParam2/dynamicParam3

I think the easiest way to integrate this, is to extract whatever is written after the slug, and add it to the target URL

**Comment by ccbikai** [comment]
I will consider this feature, but it will not be enabled by default. It can be controlled through environment variables in the future

**Comment by ccbikai** [comment]
I have implemented a simple version that can be configured using environment variables `NUXT_REDIRECT_WITH_QUERY`

https://github.com/ccbikai/Sink/blob/master/docs/configuration.md#nuxt_redirect_with_query
