### ISSUE TITLE
我的分析页面 一直提示错误请求

### ISSUE THREAD

**Issue by shaoyouvip** [ccbikai/Sink#30]
![屏幕截图 2024-07-29 155720](https://github.com/user-attachments/assets/0c0a7ba1-ae0a-4bb9-bb7e-c76f1d7181b3)

**Comment by ccbikai** [comment]
检查一下 NUXT_CF_ACCOUNT_ID 和 NUXT_CF_API_TOKEN 配置

**Comment by kimwang1978** [comment]
配置完，1个小时把10万免费额度用完了，猜测是哪里出错后反复retry导致的，请问你遇到过吗

**Comment by shaoyouvip** [comment]
> 配置完，1个小时把10万免费额度用完了，猜测是哪里出错后反复retry导致的，请问你遇到过吗

没有遇到呢！我的是正常的。
