### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by rational-stars** [ccbikai/Sink#4]
<img width="921" alt="image" src="https://github.com/ccbikai/Sink/assets/65513250/32ed14c6-3a4e-4ea7-908d-9fe1c42e66af">
Is Analytics updated in real time

**Comment by rational-stars** [comment]
<img width="1021" alt="image" src="https://github.com/ccbikai/Sink/assets/65513250/b6ba1970-8245-4f0e-b21e-d018c5136300">
Where did I make a mistake

**Comment by ccbikai** [comment]
The most likely reason for this error is that the NUXT_CF_ACCOUNT_ID and NUXT_CF_API_TOKEN are not configured correctly.

Please double-check if the analysis engine for 6.3 is open.

**Comment by rational-stars** [comment]
thank you  Try many times to succeed
