### ISSUE TITLE
A small question about deploying in cloudflare worker with backend login?

### ISSUE THREAD

**Issue by joaine-desion** [ccbikai/Sink#44]
I'm deploying in cloudflare worker, but it's having some issues, after entering the wrong password when logging into the backend, it'll stay on the loading page and the 'Unauthorized' prompt will keep surfacing in the bottom right corner, like what's going on in my picture. Sorry, I'm not sure if this is my own problem? Am I the only one experiencing this?
![screenshot-1723907583382](https://github.com/user-attachments/assets/6c1a8ec6-a6ea-464b-b80a-408971920327)

**Comment by ccbikai** [comment]
1. Check the KV binding
2. SiteToken cannot consist entirely of digits

**Comment by joaine-desion** [comment]
I've checked both options and both are fine. The problem is a bit strange, it occurs when I enter the wrong site token after refreshing a few times, and it also occurs when I log into the demo site “https://sink.cool/dashboard/login”, I'm not sure if it's my browser that's the problem, because when I change my browser it works fine, but when I repeat the operation the problem appears again. I apologize that I'm out of town on a business trip and can't use the browser on my home computer to test this, but here's the situation.
![微信图片_20240818211205](https://github.com/user-attachments/assets/31f2a096-a511-49d5-afcc-e4fd0924df95)

**Comment by joaine-desion** [comment]
> 1. 检查KV绑定
> 2. SiteToken不能完全由数字组成

I've checked both options and both are fine. The problem is a bit strange, it occurs when I enter the wrong site token after refreshing a few times, and it also occurs when I log into the demo site “https://sink.cool/dashboard/login”, I'm not sure if it's my browser that's the problem, because when I change my browser it works fine, but when I repeat the operation the problem appears again. I apologize that I'm out of town on a business trip and can't use the browser on my home computer to test this, but here's the situation.
![微信图片_20240818211205](https://github.com/user-attachments/assets/54d79b56-2cfc-498b-a100-5d531355dfe9)

**Comment by ccbikai** [comment]
Hello, which browser are you using? I'll check for compatibility

**Comment by joaine-desion** [comment]
> Hello, which browser are you using? I'll check for compatibility

firefox and Quark They all have problems like this
![Mozilla Firefox 2024_8_20 20_59_09](https://github.com/user-attachments/assets/6b2508dd-b8f5-451d-9607-a17d94b278e0)
![新标签页 - 夸克 2024_8_20 21_00_33](https://github.com/user-attachments/assets/1a87af96-fe8f-488e-b65c-adf3cc37f72d)

**Comment by ccbikai** [comment]
Fixed it, please test again using the demo site

**Comment by joaine-desion** [comment]
> Fixed it, please test again using the demo site

Great, seems to have solved it, just tested it a couple times with no problems
