### ISSUE TITLE
Unexpected content in the dashboard

### ISSUE THREAD

**Issue by cattomgithub** [ccbikai/Sink#46]
After the initial deployment, when I accessed the dashboard, I noticed something unexpected appearing at the top of the page as shown in the image. 
I would appreciate some helpful explanations and solutions. 
Thank you!

<img width="1280" alt="屏幕截图 2024-08-19 185835" src="https://github.com/user-attachments/assets/fff252a5-9c74-4594-b845-4ad00382689d">

**Comment by ccbikai** [comment]
Check if you have any JSON formatting browser extensions installed?
