### ISSUE TITLE
Case-Insensitive Links

### ISSUE THREAD

**Issue by alexh3791** [ccbikai/Sink#52]
If possible, I would like to have the option to make all links case-insensitive.

By default, Sink slugs are 5 alphanumeric characters, giving approximately 60,466,000 possible combinations of slugs (ignoring case) to make links from. Having case-sensitive links (the current default) increases the number of possible links significantly, but I feel like the overwhelming majority of Sink users will never come anywhere close to 60 million links in their instance. 

Because of this, I’d like to request to have the functionality to make Sink treat all slugs as case-insensitive, preferably by default.

In general, users are used to capitalization being of no importance in a URL. Technically, URLs are case-sensitive in situations like Sink and other link-shorteners, but most users don’t know that. They would find it confusing if they enter a URL manually in the wrong case and land at a 404 page even though it looks like they entered the correct characters.

There are a lot of situations where I think this change would be helpful, most importantly where users are entering URLs manually (especially if they always use caps lock, like many of my older coworkers). It would also be helpful in printed links on promotional material, because the link would be able to use a case structure that makes design sense in context with surrounding content.

It is also a little-known fact that QR codes can use a much more efficient mode of encoding if the data they contain only consists of [uppercase letters, numbers, and common symbols](https://github.com/zxing/zxing/wiki/Barcode-Contents#url). This is my main reason for requesting this change. If Sink were able to ignore case, the QR codes I create for links in my instance could be a lot less dense and do more in less physical space.

You can clearly see this difference in these encodings of the non-existent URL: https://1special.link 

Encoded in lowercase:
![Lowercase QR 2](https://github.com/user-attachments/assets/bf26fe58-c36d-4f14-a3ae-65645ba9748b)

Encoded in uppercase:
![Uppercase QR 2](https://github.com/user-attachments/assets/d775397b-ee85-4dba-94a3-1977c761bf61)

As you can see, the uppercase QR is significantly more optimized and efficient, making it usable at a longer distance and smaller size. If Sink didn’t care about capitalization, all of my links could use the more optimized format. 

If implemented, I think this functionality would work best as a default option, but some users with 60+M links in their instance may find it useful be able to toggle it off in order to use the entire space of possible slug combinations.

-Thanks for considering this change! Sink has been great to work with so far.

**Comment by ccbikai** [comment]
Thanks a lot for your suggestion, I initially forgot that URLs are case-insensitive.

 I will consider case-sensitivity as an option.

**Comment by alexh3791** [comment]
Thank you very much! I really enjoy Sink and look forward to using it for many years to come! It's a great tool.

**Comment by bstop-nr** [comment]
Thank you for considering this enhancement. It would also help my team if slugs were case-insensitive.

**Comment by ccbikai** [comment]
Supported from v0.1.6

https://github.com/ccbikai/Sink/releases/tag/v0.1.6

**Comment by ThrillKickerMatt** [comment]
Hey, I have a link that is not working when using different case for the SLUG. I added the short link and I capitalized the SLUG, but when I navigate using lowercase I get a 404. 

I have already tried to set the NUXT_CASE_SENSITIVE to false in CloudFlare and it still is not working when using the lowercase SLUG.

Am I missing something? ShortURL [here](https://thrlkc.kr/ZHOVAK).

**Comment by ThrillKickerMatt** [comment]
@ccbikai Do you have any idea why some links work in both upper and lower case? Why does it work differently when written out then clicked?
