### ISSUE TITLE
Suggestion: Make this repo as a template repository

### ISSUE THREAD

**Issue by cielorz** [ccbikai/Sink#53]
Shall we template this repo, to make it more easy to create own repository based on this one?

reference: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by ccbikai** [comment]
The template cannot update the code quickly. I recommend using Fork. If you have privacy needs, you can manually Clone

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-web-ui
