### ISSUE TITLE
Analytics under paywall?

### ISSUE THREAD

**Issue by slimpdev** [ccbikai/Sink#55]
Hi, i try to deploy this project yesterday, and i cant make this without pay 5$/month.
Am I doing something wrong? Are there alternatives?
The problem isn't even the $5, it's that I can't even pay it on principle since all of our cards have been blocked.
![chrome_StTVxD2Ix0](https://github.com/user-attachments/assets/17984f82-88cf-4b54-9bcf-b4801c35b39a)

**Comment by ccbikai** [comment]
I just checked the documentation, and it still supports the free version https://developers.cloudflare.com/analytics/analytics-engine/pricing/

**Comment by slimpdev** [comment]
Yes, i see this docs, but how to use it? I add this:
```
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "sink"
```
To my wrangler.toml, but project still not see it(

**Comment by najimi** [comment]
This confused me at first too. You need to check Workers & Pages > Overview and look at the right sidebar where it says Analytics Engine and make sure to enable it. You will then be able to add it to your project.

Direct link:
https://dash.cloudflare.com/?to=/:account/workers/analytics-engine

**Comment by slimpdev** [comment]
> Direct link:
> https://dash.cloudflare.com/?to=/:account/workers/analytics-engine

Yes it works! Thank you, after enable by this button i can add analytics engine to my deployment.
