### ISSUE TITLE
Links with / at the end dont work

### ISSUE THREAD

**Issue by manuls** [ccbikai/Sink#56]
Hello,

If you have a URL shorted like http://go.com/sink and you go to http://go.com/sink/ it returns a 404. I know URLs should not have a forward slash at the end, but sometimes people write it this way and it becomes a problem. Mostly because you cannot add / to the slug 

We worked it out with redirections rules in Cloudflare, but I think it can be an enhacement to have this solved.

**Comment by manuelosorio** [comment]
I noticed that as well. Made a pull request #54 a few days ago.

**Comment by ccbikai** [comment]
I‘m On Vacation. After The End, I Will Finish The Review As Soon As Possible And Merge.
