### ISSUE TITLE
Documentation "for dummies"?

### ISSUE THREAD

**Issue by Root-FTW** [ccbikai/Sink#7]
I think you need to detail more the steps of the implementation in cloudflare, I tried to deploy by myself it seemed that everything worked but it does not work to create the short links, I think I did something wrong, several steps did not come in the documentation.

I think it would be great a “For Dummies” documentation, explaining every little step and detail, even a step by step video how to deploy from scratch.

**Comment by psartek** [comment]
Opening a discord or other platform would allow the community to help each other

**Comment by ccbikai** [comment]
I just started using Discord, contact me here https://discord.gg/QnVCejuZEm .

You can also communicate on Telegram. https://t.me/htmlzone
