### ISSUE TITLE
Long url constraint in 2048 characters only

### ISSUE THREAD

**Issue by DrRingo** [ccbikai/Sink#8]
I use some hacking in url, make it soooo long and use shortening app to make it shorter to remember.

Example: in smol site, all data of the webpage contain in url only

But your constaint in 2048 characters make it impossible to use this hacking

**Comment by ccbikai** [comment]
For better compatibility, I have limited the URL length to 2048. If you have special requirements, you can fork and modify the limitation

https://github.com/ccbikai/Sink/blob/master/schemas/link.ts#L12
