### ISSUE TITLE
[Feature Request] Return Shortened Link Directly in JSON Response

### ISSUE THREAD

**Issue by abusayed0206** [ccbikai/Sink#82]
---

**Feature Request: Return Shortened Link Directly in JSON Response**

Is there a way to return the shortened link directly in the JSON response? Currently, ShareX cannot detect the dynamic link using `https://baseurl/$json:link.slug$` in the URL field.

Do you plan to make any changes to the API to support this feature?

---

I've made some changes in the `create/api` code here:

[Link to modified code](https://github.com/abusayed0206/Sink/blob/master/server/api/link/create.post.ts)

With this change, it’s working for ShareX!

---

**Comment by CRYPTO-GENIK** [comment]
This  sounds like a good idea to me as I need the API to be able to return the short link to my program

**Comment by ccbikai** [comment]
This feature has been added

```json
{
    "link": {
        "id": "629xn8cze3",
        "url": "https://sink.cool/dashboard/links",
        "slug": "debug",
        "createdAt": 1733630725,
        "updatedAt": 1733630725
    },
    "shortLink": "https://sink.cool/debug"
}
```
