### ISSUE TITLE
部署到CF一会儿把10w免费额度给用完了

### ISSUE THREAD

**Issue by kimwang1978** [ccbikai/Sink#83]
有遇到同样问题的吗。求教！

https://github.com/ccbikai/Sink/issues/39
这里我也看了，好像设上KV就好了？但是我KV已经设好了。

**Comment by ccbikai** [comment]
检查一下 KV 设置

**Comment by kimwang1978** [comment]
![image](https://github.com/user-attachments/assets/2d19ba8d-3a0b-478c-b021-6459567cd454)

多谢回复！
已经设过了，我再尝试部署一下看。

**Comment by kimwang1978** [comment]
@ccbikai KV没有什么其他特别需要设定的地方吧。
