### ISSUE TITLE
咨询短链删除问题

### ISSUE THREAD

**Issue by wangdabaoqq** [ccbikai/Sink#86]
打扰一下，想咨询下问题
1. 我当前创建了短链选择今天的时间，明天就会被删除，不添加时间则正常，咨询下该问题原因。

**_我应该从哪方面入手排查该问题_**
![image](https://github.com/user-attachments/assets/367d8a3d-bd7d-4522-b61d-2aef464a81ed)
![image](https://github.com/user-attachments/assets/4743eaab-1052-4901-8c93-fdb80730b1f2)

**Comment by wangdabaoqq** [comment]
<img width="998" alt="image" src="https://github.com/user-attachments/assets/4d15fbd2-2c03-4207-9938-a2a2f9e1095c">
<img width="987" alt="image" src="https://github.com/user-attachments/assets/f30c380a-574d-4403-a8ec-d44bd0e34667">
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/50de6446-2341-48a7-8f03-556b7beea969">
<img width="975" alt="image" src="https://github.com/user-attachments/assets/c2421474-6dbd-40ee-be0d-e4216ae0cb41">
<img width="995" alt="image" src="https://github.com/user-attachments/assets/24ac8e3d-b58a-4694-aeb7-9c1eaeb22321">
<img width="744" alt="image" src="https://github.com/user-attachments/assets/313ff317-7b9c-4ed5-ab14-a4795e22e2f8">
<img width="784" alt="image" src="https://github.com/user-attachments/assets/2ff19c26-3675-4b28-9551-5481ce99af21">
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/ddce6fdd-f6f0-4751-ac42-fc6536d79e4c">

@ccbikai

**Comment by ccbikai** [comment]
`我当前创建了短链选择今天的时间，明天就会被删除，不添加时间则正常，咨询下该问题原因。`

我理解你是在创建页面的时候，选了过期时间。 过期时间是今天，明天必然被删除。

如果要一直有效，不要选删除就行

**Comment by wangdabaoqq** [comment]
我理解问题出在哪里了
感谢！！
