### ISSUE TITLE
Links not showing

### ISSUE THREAD

**Issue by ThrillKickerMatt** [ccbikai/Sink#89]
I have two setups and everything is working correctly except one thing. I can create new links and the Analytics is showing appropriately. The Links tab just shows a spinning wheel and never shows my links. I can see them if I go into the analytics, then find and open the SLUG. Only then can I see the QR code and the comments.

I have already redeployed the projects successfully in CloudFlare. I have verified the links do work and I have verified that I can see the configuration for them in the KV values.

Any ideas why this is happening?

**Comment by AdamCarballo** [comment]
I have the same issue, and I just finished deploying it
It seems the DEMO site also is broken, with 500 errors spamming the console.

Looking at the CF logs, there seems to be some cursor issue:

```{
  "truncated": false,
  "executionModel": "stateless",
  "outcome": "ok",
  "scriptVersion": {
    "id": "932ac9d7-b469-4b6f-REDACTED"
  },
  "scriptName": "pages-worker--REDACTED-production",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "[nuxt] [request error] [unhandled] [500]",
        "KV GET failed: 400 Invalid cursor\n"
      ],
      "level": "error",
      "timestamp": 1733444245015
    }
  ],
  "eventTimestamp": 1733444245013,
  "event": {
    "request": {
      "url": "https://[REDACTED]/api/link/list?limit=24&cursor",
      "method": "GET",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, br",
        "accept-language": "en-US",
        "authorization": "REDACTED",
        "cf-connecting-ip": "REDACTED",
        "cf-connecting-o2o": "1",
        "cf-ipcountry": "REDACTED",
        "cf-ray": "REDACTED",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "REDACTED",
        "priority": "u=1, i",
        "referer": "https://[REDACTED]/dashboard/links",
        "sec-ch-ua": "\"Google Chrome\";v=\"131\", \"Chromium\";v=\"131\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
        "x-forwarded-for": "REDACTED",
        "x-forwarded-proto": "https",
        "x-real-ip": "REDACTED"
      }```

**Comment by ThrillKickerMatt** [comment]
Thanks, I figured it was a larger issue and not something I did wrong.

**Comment by raguventhan** [comment]
means there is a problem with Cloudflare or do we need to something to resolve this problem.

**Comment by raguventhan** [comment]
I have updated the server\api\link\list.get.ts like follows, it fixed the problem for me.

import { z } from 'zod'

export default eventHandler(async (event) => {
  const { cloudflare } = event.context
  const { KV } = cloudflare.env
  if (!KV) {
    console.error("KV Store not initialized.");
    return { error: "KV Store not available." };
  }
  try {
  const { limit, cursor } = await getValidatedQuery(event, z.object({
    limit: z.coerce.number().max(1024).default(20),
    cursor: z.string().trim().max(1024).optional(),
  }).parse)
  const list = await KV.list({
    prefix: `link:`,
    limit,
    cursor,
  })
  if (Array.isArray(list.keys)) {
    list.links = await Promise.all(list.keys.map(async (key: { name: string }) => {
      const { metadata, value: link } = await KV.getWithMetadata(key.name, { type: 'json' })
      if (link) {
        return {
          ...metadata,
          ...link,
        }
      }
      return link
    }))
  }
  delete list.keys
    return list
  } catch (error) {
    console.error("Unexpected error:", error);
    return { error: "Internal Server Error" };
  }
})

**Comment by ccbikai** [comment]
The Cloudflare API has been updated, I just updated the code. Everyone needs to update to the latest code.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-web-ui

**Comment by raguventhan** [comment]
Actual fix:

components\dashboard\links\Index.vue

![image](https://github.com/user-attachments/assets/c305b311-d707-4138-bca3-cc10eb37117b)

**Comment by hdeyana** [comment]
Is hotfix already release?

**Comment by ccbikai** [comment]
> Is hotfix already release? it impact production app

Updates have been released, update the code in this way. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-web-ui

**Comment by Angiin** [comment]
> Fix by @ccbikai
> 
> components\dashboard\links\Index.vue
> 
> ![image](https://private-user-images.githubusercontent.com/26790271/393127696-c305b311-d707-4138-bca3-cc10eb37117b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMTEwMzQsIm5iZiI6MTczNTExMDczNCwicGF0aCI6Ii8yNjc5MDI3MS8zOTMxMjc2OTYtYzMwNWIzMTEtZDcwNy00MTM4LWJjYTMtY2MxMGViMzcxMTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA3MTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZDM5ODdjNDk2MDFmNWNhMmVhNjQ0NmE0MzNjNTY2ZWY3ZjFjNjcwOGE5YWExNTYxMDA0YmYxYzlhZTViZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GjklixhpDIkhO77guNDKA7IZPIUdPaRdqS8iNGP8HLg)

Thanks, it really solves this issue
