### ISSUE TITLE
KV GET Failed: 400 invalid cursor

### ISSUE THREAD

**Issue by seriaati** [ccbikai/Sink#90]
I can't see my created links on my dashboard, so I checked the network requests, and found out that requests to `api/link/list?limit=24&cursor` all result in http status code 500.
![image](https://github.com/user-attachments/assets/d9008d1c-59e8-4330-951a-ea0c264a2831)

I should also suggest to set a max retry limit because the page just spams the API endpoint, causing the KV usage to skyrocket.
![image](https://github.com/user-attachments/assets/6c3b6deb-bf2c-447c-a863-fae2080c10d7)

**Comment by xinshoutw** [comment]
You can try click Sync fork, it solved same problem to me.

![Arc 2024-12-08 at 06 14 06@2x](https://github.com/user-attachments/assets/27d33c40-000f-46d7-9363-d3d90815e502)

**Comment by xinshoutw** [comment]
btw, if you use [sink-extension](https://github.com/zhuzhuyule/sink-extension) too, the latest version still have the same issue, just remove "&cursor" at the end of request "request(`/api/link/list?limit=${count}&cursor`)".

![Arc 2024-12-08 at 06 17 44@2x](https://github.com/user-attachments/assets/94a1c069-c23a-4f07-a509-f10b61cc3eca)

Have a good day.
xinshou

**Comment by seriaati** [comment]
Thanks, that solved the issue.
