### ISSUE TITLE
[Feature request] Integrate the login page into the index page

### ISSUE THREAD

**Issue by sczat** [ccbikai/Sink#93]
There are a few too many steps to perform
First you need to enter the URL to enter the site, then press dashboard to log in, and then press create link.
It might be a good idea to integrate the login page into the index page.
e.g.
![image](https://github.com/user-attachments/assets/54639991-6dcf-4430-ae39-494f31d4496c)

**Comment by xinshoutw** [comment]
It's work for me. Set the environment variable of "NUXT_HOME_URL" to https://{MY_DOMAIN}/dashboard/

**Comment by sczat** [comment]
I just saw it in the docs.
This is working great.
Thanks for your prompt reply and help!
